services:
  streamlit-dev:
    container_name: streamlit-dev
    image: dashboard/streamlit-dev:latest
    restart: unless-stopped
    volumes:
      - ./src:/app
      - ./.streamlit:/app/.streamlit
      - ./data:/app/data
    ports:
      - 8080:8080
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    environment:
      - STREAMLIT_SERVER_PORT=8080 #This needs to match exposed port in Dockerfile. See https://github.com/bigjoedata/streamlit-plus for dockerfile
    # You may need to uncomment these for some use cases
    # - enableCORS=false
    # - enableXsrfProtection=false
    command: streamlit run main.py
