FROM python:3.10-slim-buster AS builder

ENV PATH=/root/.local:/root/.local/bin:/install:$PATH

WORKDIR /app

COPY pyproject.toml ./pyproject.toml

RUN pip install --upgrade pip && \
    pip install --user poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi && \
    rm -rf /root/.cache/pip

FROM python:3.10-slim-buster AS development
COPY --from=builder /root/.local /root/.local
COPY --from=builder /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin
COPY .streamlit /app/.streamlit
ENV PATH=/root/.local:/root/.local/bin:${PATH}
ENV PATH=/root/.local/bin:${PATH}

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

EXPOSE 8080
WORKDIR /app

