FROM python:3.10-slim-buster AS builder

ENV PATH=/root/.local:/root/.local/bin:/install:$PATH

WORKDIR /app

RUN pip install --upgrade pip
RUN pip install --user poetry
COPY pyproject.toml ./pyproject.toml
RUN poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi

COPY src /app

FROM python:3.10-slim-buster AS development
COPY --from=builder /root/.local /root/.local
COPY --from=builder /app/main.py /app/main.py
ENV PATH=/root/.local:/root/.local/bin:$PATH

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

EXPOSE 8080
WORKDIR /app

CMD streamlit run main.py
